# Generated by Django 3.2 on 2021-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211014_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(upload_to='brochures'),
        ),
    ]
