# Generated by Django 3.2 on 2021-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
