# Generated by Django 3.2 on 2021-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211014_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(blank=True, max_length=250, null=True, verbose_name='About attestant')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Text Testimonial (If any)')),
                ('location', models.FileField(blank=True, null=True, upload_to='testimonial/')),
                ('display_on_homepage', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
