# Generated by Django 3.2 on 2023-06-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0064_auto_20230510_0447'),
        ('events', '0012_jobfair_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='students',
        ),
        migrations.CreateModel(
            name='JobFairAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.student')),
            ],
        ),
    ]
