# Generated by Django 3.2.19 on 2023-08-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='City (Company Headquarters)'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description about the company'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='emp_contact',
            field=models.CharField(default=123, max_length=17, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='emp_name',
            field=models.CharField(default='abc', max_length=200, verbose_name='Company HR Representative Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='State (Company Headquarters)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
