# Generated by Django 3.2.19 on 2023-08-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0065_auto_20230705_1713'),
        ('registration_api', '0002_auto_20230831_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
