# Generated by Django 3.2.19 on 2023-09-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0065_auto_20230705_1713'),
        ('registration_api', '0003_auto_20230831_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.job')),
            ],
        ),
    ]
