# Generated by Django 3.2 on 2021-07-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdlUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('auth', models.CharField(max_length=60)),
                ('confirmed', models.IntegerField()),
                ('gender', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('age_range', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('academic_code', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('organizer', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('invigilator', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('flag', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('mnethostid', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=96)),
                ('idnumber', models.CharField(max_length=765)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('icq', models.CharField(max_length=45)),
                ('skype', models.CharField(max_length=150)),
                ('yahoo', models.CharField(max_length=150)),
                ('aim', models.CharField(max_length=150)),
                ('msn', models.CharField(max_length=150)),
                ('phone1', models.CharField(max_length=60)),
                ('phone2', models.CharField(max_length=60)),
                ('institution', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=210)),
                ('city', models.CharField(max_length=360)),
                ('country', models.CharField(max_length=6)),
                ('theme', models.CharField(max_length=150)),
                ('timezone', models.CharField(max_length=300)),
                ('lastip', models.CharField(max_length=135)),
                ('secret', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=765)),
                ('description', models.TextField(blank=True)),
                ('imagealt', models.CharField(blank=True, max_length=765)),
            ],
            options={
                'db_table': 'mdl_user',
            },
        ),
        migrations.CreateModel(
            name='MdlQuizGrades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz', models.BigIntegerField()),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timemodified', models.BigIntegerField()),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moodle.mdluser')),
            ],
            options={
                'db_table': 'mdl_quiz_grades',
            },
        ),
    ]
