# Generated by Django 3.2 on 2021-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdlQuiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('introformat', models.SmallIntegerField()),
                ('timeopen', models.BigIntegerField()),
                ('timeclose', models.BigIntegerField()),
                ('preferredbehaviour', models.CharField(max_length=32)),
                ('attempts', models.IntegerField()),
                ('attemptonlast', models.SmallIntegerField()),
                ('grademethod', models.SmallIntegerField()),
                ('decimalpoints', models.SmallIntegerField()),
                ('questiondecimalpoints', models.SmallIntegerField()),
                ('reviewattempt', models.IntegerField()),
                ('reviewcorrectness', models.IntegerField()),
                ('reviewmarks', models.IntegerField()),
                ('reviewspecificfeedback', models.IntegerField()),
                ('reviewgeneralfeedback', models.IntegerField()),
                ('reviewrightanswer', models.IntegerField()),
                ('reviewoverallfeedback', models.IntegerField()),
                ('questionsperpage', models.BigIntegerField()),
                ('shufflequestions', models.SmallIntegerField()),
                ('shuffleanswers', models.SmallIntegerField()),
                ('questions', models.TextField()),
                ('sumgrades', models.DecimalField(decimal_places=5, max_digits=10)),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timecreated', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('timelimit', models.BigIntegerField()),
                ('overduehandling', models.CharField(max_length=16)),
                ('graceperiod', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=255)),
                ('browsersecurity', models.CharField(max_length=32)),
                ('delay1', models.BigIntegerField()),
                ('delay2', models.BigIntegerField()),
                ('showuserpicture', models.SmallIntegerField()),
                ('showblocks', models.SmallIntegerField()),
                ('navmethod', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'mdl_quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdlQuizGrades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('grade', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_quiz_grades',
                'managed': False,
            },
        ),
    ]
