# Generated by Django 3.2.19 on 2023-08-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_alter_mdlquizgrades_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdluser',
            name='academic_code',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='icq',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='mdluser',
            name='organizer',
        ),
    ]
