# Generated by Django 3.2 on 2021-04-28 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=400)),
                ('institute', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('end_year', models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)])),
                ('gpa', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=400)),
                ('about', models.TextField()),
                ('experience', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('cover_letter', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.degree')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('salary_range_min', models.IntegerField()),
                ('salary_range_max', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('benefits', models.TextField()),
                ('status', models.BooleanField()),
                ('requirements', models.TextField()),
                ('shift_time', models.CharField(max_length=200)),
                ('key_job_responsibilities', models.TextField()),
                ('gender', models.CharField(choices=[('f', 'f'), ('m', 'm'), ('o', 'other')], max_length=10)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.domain')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_contact', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=400)),
                ('company_size', models.CharField(choices=[('< 50', '< 50'), ('50 - 100', '50 - 100'), ('100 - 500', '100 - 500'), ('> 500', '> 500')], max_length=25)),
                ('website', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
