# Generated by Django 3.2 on 2021-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.ManyToManyField(null=True, to='emp.Education'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(null=True, to='emp.Skill'),
        ),
        migrations.AlterField(
            model_name='student',
            name='spk_institute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='spk_usr_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
