# Generated by Django 3.2 on 2021-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Delhi', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default='Delhi', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='CP', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='Delhi', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
