# Generated by Django 3.2 on 2021-05-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20210531_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobshortlist',
            name='slug',
        ),
        migrations.AddField(
            model_name='jobshortlist',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.student'),
            preserve_default=False,
        ),
    ]
