# Generated by Django 3.2 on 2021-06-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20210531_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.degree'),
        ),
    ]
