# Generated by Django 3.2 on 2021-05-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_student_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='institute',
        ),
    ]
