# Generated by Django 3.2 on 2021-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_job_activation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
