# Generated by Django 3.2 on 2021-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20210611_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description About Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.CharField(max_length=250, verbose_name='Designation (Job Position)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('f', 'F-Female Candidates'), ('m', 'M-Male Candidates'), ('a', 'No Criteria')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='key_job_responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Key Job Responsibilities'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_app_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Application Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Qualifications/Skills Required'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title of the job page'),
        ),
    ]
