# Generated by Django 3.2 on 2021-06-14 08:50

from django.db import migrations, models
import emp.models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_student_spk_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=emp.models.user_directory_path),
        ),
    ]
