# Generated by Django 3.2 on 2021-04-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20210429_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm'), ('a', 'No criteria')], max_length=10),
        ),
    ]
