# Generated by Django 3.2 on 2021-06-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_alter_student_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
