# Generated by Django 3.2 on 2021-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_alter_student_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
