# Generated by Django 3.2 on 2021-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_student_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_vacancies',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
