# Generated by Django 3.2 on 2021-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_job_num_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='emp.Project'),
        ),
    ]
