# Generated by Django 3.2 on 2021-06-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_auto_20210622_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='alternative_email',
            new_name='alternate_email',
        ),
    ]
