# Generated by Django 3.2 on 2021-06-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0014_rename_alternative_email_student_alternate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='acad_discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.discipline'),
            preserve_default=False,
        ),
    ]
