# Generated by Django 3.2 on 2021-06-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_auto_20210622_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='education',
            name='acad_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.discipline', verbose_name='Academic Discipline'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
