# Generated by Django 3.2 on 2021-06-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0020_auto_20210625_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About Yourself'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Home Address'),
        ),
    ]
