# Generated by Django 3.2 on 2021-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0023_auto_20210630_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.ManyToManyField(blank=True, to='emp.Degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='discipline',
            field=models.ManyToManyField(blank=True, to='emp.Discipline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='institute_type',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
