# Generated by Django 3.2 on 2021-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0024_auto_20210630_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.IntegerField(blank=True, null=True)),
                ('mdl_course', models.IntegerField(blank=True, null=True)),
                ('mdl_quiz', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_foss',
            field=models.ManyToManyField(blank=True, null=True, to='emp.Foss'),
        ),
    ]
