# Generated by Django 3.2 on 2021-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0026_auto_20210630_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
