# Generated by Django 3.2 on 2021-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0027_degree_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.ManyToManyField(blank=True, related_name='degrees', to='emp.Degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='discipline',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='emp.Discipline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_foss',
            field=models.ManyToManyField(blank=True, null=True, related_name='fosses', to='emp.Foss'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
