# Generated by Django 3.2 on 2021-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0028_auto_20210701_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='type',
            new_name='jobtype',
        ),
    ]
