# Generated by Django 3.2 on 2021-07-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0030_alter_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_status',
            field=models.IntegerField(blank=True, choices=[(None, '--------'), (1, 'Active'), (3, 'Deactive')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.domain', verbose_name='Job Sector'),
        ),
        migrations.AlterField(
            model_name='job',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test Date From'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('a', 'No Criteria'), ('f', 'F-Female Candidates'), ('m', 'M-Male Candidates')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Maximum)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Minimum)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='shift_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test Date Upto'),
        ),
    ]
