# Generated by Django 3.2 on 2021-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0031_auto_20210705_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_c',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('less_than_50', '< 50'), ('50_100', '50 - 100'), ('100_500', '100 - 500'), ('greater_than_500', '> 500')], default='100_500', max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_c',
            field=models.IntegerField(null=True, verbose_name='State (Company Headquarters)'),
        ),
    ]
