# Generated by Django 3.2 on 2021-07-23 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0033_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistEmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('email_sequence', models.IntegerField(blank=True, null=True)),
                ('total_mails', models.IntegerField()),
                ('success_mails', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('log_file', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Invalid.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
