# Generated by Django 3.2 on 2021-07-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0036_auto_20210728_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_c',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_c',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='State (Company Headquarters)'),
        ),
    ]
