# Generated by Django 3.2 on 2021-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0038_auto_20210728_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_c',
            field=models.IntegerField(null=True, verbose_name='City (Company Headquarters)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_c',
            field=models.IntegerField(null=True, verbose_name='State (Company Headquarters)'),
        ),
    ]
