# Generated by Django 3.2 on 2021-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0039_auto_20210728_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='City (Company Headquarters)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='State (Company Headquarters)'),
        ),
    ]
