# Generated by Django 3.2 on 2021-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0040_auto_20210728_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city_job',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state_job',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
