# Generated by Django 3.2 on 2021-07-31 17:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0041_auto_20210728_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='emp_contact',
            field=models.CharField(default='9810150179', max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_app_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Application Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
