# Generated by Django 3.2 on 2021-08-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0042_auto_20210731_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
