# Generated by Django 3.2 on 2021-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0044_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description about image')),
                ('location', models.FileField(upload_to='gallery/')),
                ('display_on_homepage', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(blank=True, max_length=250, null=True, verbose_name='About attestant')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Text Testimonial (If any)')),
                ('location', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('display_on_homepage', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
