# Generated by Django 3.2 on 2021-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0046_auto_20210806_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
