# Generated by Django 3.2 on 2021-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0047_auto_20210806_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
