# Generated by Django 3.2 on 2021-08-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0048_auto_20210806_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Your Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.FileField(blank=True, null=True, upload_to='testimonial/'),
        ),
    ]
