# Generated by Django 3.2 on 2021-08-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0049_auto_20210809_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
    ]
