# Generated by Django 3.2 on 2021-10-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0050_remove_testimonial_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
