# Generated by Django 3.2 on 2021-10-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0051_delete_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
