# Generated by Django 3.2 on 2022-03-21 06:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0053_auto_20220310_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.ManyToManyField(blank=True, related_name='domains', to='emp.Discipline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='key_job_responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Key Job Responsibilities'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Qualifications/Skills Required'),
        ),
    ]
