# Generated by Django 3.2 on 2022-04-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0056_student_notified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
