# Generated by Django 3.2 on 2023-01-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0058_auto_20230120_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistemailstatus',
            name='message',
            field=models.TextField(default='Data is not available. Data is available only for mails sent after 21st Jan, 2023'),
        ),
        migrations.AlterField(
            model_name='shortlistemailstatus',
            name='subject',
            field=models.CharField(default='Data is not available. Data is available only for mails sent after 21st Jan, 2023', max_length=255),
        ),
    ]
