# Generated by Django 3.2 on 2023-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0060_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avail_for_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_immediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='willing_to_relocate',
            field=models.JSONField(null=True),
        ),
    ]
