# Generated by Django 3.2 on 2023-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0061_auto_20230427_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avail_for_intern',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_immediate',
            field=models.BooleanField(null=True),
        ),
    ]
