# Generated by Django 3.2 on 2023-05-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0063_auto_20230427_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': ['name']},
        ),
    ]
