# Generated by Django 3.0.5 on 2021-04-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import emp.models
import emp.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=' ', max_length=50)),
                ('comment', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact_stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default=' ', max_length=100, verbose_name='Representative Name')),
                ('company_name', models.CharField(max_length=300, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, default='pro1.png', null=True, upload_to='')),
                ('company_description', models.TextField(default=' ', max_length=2000, verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default=' ', max_length=200)),
                ('joblocation', models.CharField(max_length=200)),
                ('jobskills', models.TextField(max_length=500)),
                ('jobdescription', models.TextField(max_length=2000)),
                ('jobcategory', models.CharField(default=' ', max_length=100)),
                ('criteria', models.CharField(default=' ', max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, default='On Review', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='payUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=130)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rating', models.IntegerField(blank=True)),
                ('suggestion', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=400)),
                ('university', models.CharField(default=' ', max_length=250)),
                ('startyear', models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='startyear')),
                ('endyear', models.IntegerField(blank=True, choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2021, verbose_name='endyear')),
                ('gpa', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('skills', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('experience', models.TextField(default=' ', max_length=1000)),
                ('Spokentest_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('about', models.TextField(default=' ', max_length=2000)),
                ('pic', models.ImageField(blank=True, default='pro1.png', null=True, upload_to='')),
                ('github', models.URLField(blank=True, default=' ', max_length=300, null=True)),
                ('Linkedin', models.URLField(blank=True, default=' ', max_length=300, null=True)),
                ('upload_your_work', models.FileField(storage=emp.storage.OverwriteStorage(), upload_to=emp.models.user_directory_path)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.Course')),
                ('degree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.Degree')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(default='', max_length=100)),
                ('ename', models.CharField(default='', max_length=100)),
                ('jtitle', models.CharField(default='', max_length=200)),
                ('statu', models.IntegerField(blank=True)),
                ('jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobs')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.student')),
            ],
        ),
        migrations.CreateModel(
            name='spoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.student')),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('target', models.CharField(choices=[('1', 'User'), ('2', 'students'), ('3', 'employer')], default='1', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blogcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appliedjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('jobs', models.ManyToManyField(blank=True, to='emp.jobs')),
                ('student', models.ManyToManyField(blank=True, to='emp.student')),
            ],
        ),
    ]
