# Generated by Django 3.0.5 on 2021-01-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0084_remove_pay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='endyear',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='endyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(blank=True, default=' ', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='startyear',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='startyear'),
        ),
        migrations.CreateModel(
            name='spoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.student')),
            ],
        ),
    ]
