# Generated by Django 3.2 on 2021-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_institutetype',
                'managed': False,
            },
        ),
    ]
