# Generated by Django 3.2.19 on 2023-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0003_language_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdlemail', models.EmailField(max_length=255, null=True)),
                ('mdlcourse_id', models.PositiveIntegerField(default=0)),
                ('mdlquiz_id', models.PositiveIntegerField(default=0)),
                ('mdlattempt_id', models.PositiveIntegerField(default=0)),
                ('part_status', models.PositiveSmallIntegerField(default=0)),
                ('mdlgrade', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('cert_code', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'training_eventteststatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('stcount', models.PositiveIntegerField(default=0)),
                ('batch_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'events_studentbatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_studentmaster',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'managed': False},
        ),
    ]
