# Generated by Django 3.2.19 on 2023-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0004_auto_20230830_1113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='creation_language',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='training_participant',
        ),
    ]
