GET http://127.0.0.1:8000/api/disciplines HTTP/1.1

###
POST http://127.0.0.1:8000/api/disciplines/ HTTP/1.1
content-type: application/json

{
    "name": "ruhi"
    
}

###
GET http://127.0.0.1:8000/api/disciplines/2 HTTP/1.1

###
PATCH http://127.0.0.1:8000/api/disciplines/2/ HTTP/1.1
content-type: application/json

{
  "name":"illu"
}

###
DELETE http://127.0.0.1:8000/api/disciplines/2  HTTP/1.1